export const allProducts = [
  {
    id:1,
    name:'Electro-Acoustic Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jWtZr79/guitar1.webp',
    seller: 'Fender',
  },
  {
    id:2,
    name:'Violin',
    price: '205.95',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/pbpWbb7/violin.webp',
    seller: 'Yamaha',
  },
  {
    id:3,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:4,
    name:'2 Coldplay Ticket',
    price: '320.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jRqBNPt/coldplay.jpg',
    seller: 'Seller 1',
  },
  {
    id:5,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:6,
    name:'Electro-Acoustic Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jWtZr79/guitar1.webp',
    seller: 'Seller 1',
  },
  {
    id:7,
    name:'2 Coldplay Ticket',
    price: '320.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jRqBNPt/coldplay.jpg',
    seller: 'Seller 1',
  },
  {
    id:8,
    name:'Violin',
    price: '205.95',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/pbpWbb7/violin.webp',
    seller: 'Seller 1',
  },
  {
    id:9,
    name:'Amplifier Guitar',
    price: '310.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:10,
    name:'Electro-Acoustic Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jWtZr79/guitar1.webp',
    seller: 'Seller 1',
  },
  {
    id:11,
    name:'Violin',
    price: '205.95',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/pbpWbb7/violin.webp',
    seller: 'Seller 1',
  },
  {
    id:12,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:13,
    name:'2 Coldplay Ticket',
    price: '320.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jRqBNPt/coldplay.jpg',
    seller: 'Seller 1',
  },
  {
    id:14,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },{
    id:15,
    name:'Electro-Acoustic Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jWtZr79/guitar1.webp',
    seller: 'Seller 1',
  },
  {
    id:16,
    name:'Violin',
    price: '205.95',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/pbpWbb7/violin.webp',
    seller: 'Seller 1',
  },
  {
    id:17,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:18,
    name:'2 Coldplay Ticket',
    price: '320.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jRqBNPt/coldplay.jpg',
    seller: 'Seller 1',
  },
  {
    id:19,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
  {
    id:20,
    name:'Electro-Acoustic Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jWtZr79/guitar1.webp',
    seller: 'Seller 1',
  },
  {
    id:21,
    name:'2 Coldplay Ticket',
    price: '320.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/jRqBNPt/coldplay.jpg',
    seller: 'Seller 1',
  },
  {
    id:22,
    name:'Amplifier Guitar',
    price: '225.00',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    img:'https://i.ibb.co/XVHds8X/Amplificador-Boss-Katana-Head-MKII-Musical-cedar.png',
    seller: 'Seller 1',
  },
]